config/routes.rb
Rails.application.routes.draw do
  get 'patients/index'

  resources :patients do
    resources :notes
  end

  root 'patients#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :patient
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :notes, dependent: :destroy
  validates :name, presence: true,
                   length: { minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def create
    @patient = Patient.find(params[:patient_id])
    @note = @patient.notes.create(note_params)
    redirect_to patient_path(@patient)
  end

  def edit
    @patient = Patient.find(params[:patient_id])
    @note = @patient.notes.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:patient_id])
    @note = @patient.notes.find(params[:id])

    if @note.update(note_params)
      redirect_to @patient
    else
      render 'edit'
    end
  end

  def destroy
    @patient = Patient.find(params[:patient_id])
    @note = @patient.notes.find(params[:id])
    @note.destroy
    redirect_to patient_path(@patient)
  end

  private
    def note_params
      params.require(:note).permit(:doctor, :body)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @patients = Patient.all
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def new
    @patient = Patient.new
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def create
    @patient = Patient.new(patient_params)

    if @patient.save
      redirect_to @patient
    else
      render 'new'
    end
  end

  def update
    @patient = Patient.find(params[:id])

    if @patient.update(patient_params)
      redirect_to @patient
    else
      render 'edit'
    end
  end

  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy

    redirect_to patients_path
  end

  private
    def patient_params
      params.require(:patient).permit(:name, :address, notes_attributes: [:body, :doctor])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: [ @patient, note ], local: true) do |form| %>

  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@patient.errors.count, "error") %> prohibited
        this patient from being saved:
      </h2>
      <ul>
        <% @patient.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :note %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.label :doctor %><br>
    <%= form.text_field :doctor %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/notes/_note.html.erb
<p>
  <strong>Note:</strong>
  <%= note.body %>
</p>

<p>
  <strong>Doctor:</strong>
  <%= note.doctor %>
</p>

<p>
  <tr>
    <td><%= link_to 'Delete', [note.patient, note],
               method: :delete,
               data: { confirm: 'Are you sure you want to delete this note?' } %></td>

    <td><%= link_to 'Edit', edit_patient_note_path(@patient, note)%></td>
  </tr>
</p>

app/views/notes/edit.html.erb
<h1>Edit Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', patient_path(@patient) %>

app/views/patients/_form.html.erb
<%= form_with model: @patient, local: true do |form| %>

  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@patient.errors.count, "error") %> prohibited
        this patient from being saved:
      </h2>
      <ul>
        <% @patient.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :address %><br>
    <%= form.text_area :address %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/patients/edit.html.erb
<h1>Edit Patient</h1>

<%= render 'form'%>

<%= link_to 'Back', patient_path(@patient) %>

app/views/patients/index.html.erb
<h1>Patient List</h1>

<%= link_to 'New patient', new_patient_path %>

<table>
  <tr>
    <th>Patient</th>
    <th>Address</th>
  </tr>

  <% @patients.each do |patient| %>
    <tr>
      <td><%= patient.name %></td>
      <td><%= patient.address %></td>
      <td><%= link_to 'Show', patient_path(patient) %></td>
      <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
      <td><%= link_to 'Delete', patient_path(patient),
          method: :delete,
          data: { confirm: 'Are you sure you would like to delete patient: ' + patient.name + '?' } %></td>
    </tr>
  <% end %>
</table>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<h2>Patient Infomration</h2>
<p>
  <strong>Name:</strong>
  <%= @patient.name %>
</p>

<p>
  <strong>Addresss:</strong>
  <%= @patient.address %>
</p>
<%= link_to 'Edit', edit_patient_path(@patient) %>

<h2>Notes</h2>
<%= render @patient.notes %>

<h2>Add a note:</h2>
<%= render 'notes/form', note: @patient.notes.build %>

<%= link_to 'Back', patients_path %>